POST http://localhost:5000/models
Content-Type: application/json

{
    "name": "Mazda 6",
    "hour_price": 3.25
}

###
POST http://localhost:5000/vehicles
Content-Type: application/json

###
GET http://localhost:5000/modelscount
Content-Type: application/json